# Generated by Django 4.2.4 on 2023-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id чата в телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_login',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='логин пользователя в телеграм'),
        ),
    ]
