# Generated by Django 4.2.4 on 2023-08-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(default='10:00')),
                ('action', models.CharField(blank=True, max_length=150, null=True, verbose_name='Действие')),
                ('frequency', models.SmallIntegerField(default=1, verbose_name='Периодичность напоминания в днях')),
                ('execution_time', models.TimeField(default='00:01')),
                ('is_public', models.BooleanField(choices=[(True, 'публичная'), (False, 'личная')], verbose_name='Кому видна привычка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
            ],
            options={
                'verbose_name': 'Хорошая привычка',
                'verbose_name_plural': 'Хорошие привычки',
            },
        ),
        migrations.CreateModel(
            name='GoodHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(default='10:00')),
                ('action', models.CharField(blank=True, max_length=150, null=True, verbose_name='Действие')),
                ('frequency', models.SmallIntegerField(default=1, verbose_name='Периодичность напоминания в днях')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(default='00:01')),
                ('is_public', models.BooleanField(choices=[(True, 'публичная'), (False, 'личная')], verbose_name='Кому видна привычка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.pleasanthabit', verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
            ],
            options={
                'verbose_name': 'Хорошая привычка',
                'verbose_name_plural': 'Хорошие привычки',
            },
        ),
    ]
