# Generated by Django 4.2.4 on 2023-08-08 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodhabit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Кому видна привычка'),
        ),
        migrations.AlterField(
            model_name='goodhabit',
            name='last_reminder_date',
            field=models.DateField(default=datetime.date(2023, 8, 8), verbose_name='Дата последнего напоминания'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Кому видна привычка'),
        ),
        migrations.AlterField(
            model_name='pleasanthabit',
            name='last_reminder_date',
            field=models.DateField(default=datetime.date(2023, 8, 8), verbose_name='Дата последнего напоминания'),
        ),
    ]
