# Generated by Django 4.2.4 on 2023-08-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pleasanthabit',
            options={'verbose_name': 'Приятная привычка', 'verbose_name_plural': 'Приятные привычки'},
        ),
        migrations.AlterField(
            model_name='goodhabit',
            name='execution_time',
            field=models.TimeField(default='00:01', verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='goodhabit',
            name='time',
            field=models.TimeField(default='10:00', verbose_name='Время напоминания'),
        ),
    ]
