# Generated by Django 4.2.4 on 2023-08-05 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_pleasanthabit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodhabit',
            name='last_reminder_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего напоминания'),
        ),
        migrations.AddField(
            model_name='pleasanthabit',
            name='last_reminder_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего напоминания'),
        ),
    ]
