# Generated by Django 4.2.4 on 2023-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_goodhabit_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasanthabit',
            name='execution_time',
            field=models.TimeField(default='00:01', verbose_name='Время выполнения'),
        ),
    ]
