# Generated by Django 4.2.4 on 2023-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_goodhabit_last_reminder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodhabit',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'публичная'), (False, 'личная')], default=False, verbose_name='Кому видна привычка'),
        ),
    ]
